pipeline:
  name: GitHubActions_Harness
  identifier: GitHubActions_Harness
  projectIdentifier: GitHubHarnessAKSPoC
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy_On_AKS
        identifier: Deploy_On_AKS
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: AKS
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: AKSDeployment
            deployToAll: false
            infrastructureDefinitions:
              - identifier: AKSInfra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
