deployment:
  name: githubactions-harness-deployment
  replicas: 2

app:
  name: githubactionsharness
  env: poc

container:
  name: githubactionspoc
  image: githubactionsharness.azurecr.io/githubactionsharness:latest
  imagePullPolicy: Always
  port: 8080

service:
  name: githubactions-harness-svc
  selector:
    app: githubactionsharness
  type: LoadBalancer
  ports:
    http: 80
    targetPort: 8080

hpa:
  name: githubactions-harness-hpa
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: githubactions-harness-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20

