deployment:
  name: githubactionspoc
  replicas: 1

app:
  name: githubactionsharness
  env: poc

container:
  name: githubactionspoc
  image: githubactionsharness.azurecr.io/githubactionsharness:latest
  imagePullPolicy: Always
  command: /bin/bash
  args: "dd if=/dev/zero of=/dev/null"
  port: 8080

service:
  name: githubactionspoc-svc
  selector:
    app: githubactionsharness
  type: LoadBalancer
  ports:
    http: 80
    targetPort: 8080
