apiVersion: apps/v1
kind: Deployment
metadata:
  name: githubactionspoc
  labels:
    app: githubactionsharness
    env: poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: githubactionsharness
  template:
    metadata:
      labels:
        app: githubactionsharness
        env: poc
    spec:
      containers:
      - name: githubactionspoc
        image: githubactionsharness.azurecr.io/githubactionsharness:latest
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args:
         - "dd if=/dev/zero of=/dev/null"

        ports:
        - name:  http
          containerPort: 8080
          protocol: TCP
