apiVersion: apps/v1
kind: Deployment
metadata:
  name: githubactionspoc
  labels:
    app: githubactions-harness-poc
    env: poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: githubactions-harness-poc
  template:
    metadata:
      labels:
        app: harness
        env: poc
    spec:
      containers:
      - name: githubactionspoc
        image: githubactionsharness.azurecr.io/githubactionsharness:latest
        imagePullPolicy: Always
        command:
        - /bin/sh
        - -c
        - "while true; do wget -q -O- http://php-apache; done"
        
        ports:
        - name:  http
          containerPort: 8080
          protocol: TCP
