apiVersion: apps/v1
kind: Deployment
metadata:
  name: githubactionspoc
  labels:
    app: harness
    env: poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harness
  template:
    metadata:
      labels:
        app: harness
        env: poc
    spec:
      containers:
      - name: githubactionspoc
        image: githubactionsharness.azurecr.io/githubactionsharness:520186ad960b3f7191f2dbe82c2def3dd171f039

        ports:
        - name:  http
          containerPort: 8080
          protocol: TCP
