apiVersion: apps/v1
kind: Deployment
metadata:
  name: githubactionspoc
  labels:
    app: harness
    env: poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harness
  template:
    metadata:
      labels:
        app: harness
        env: poc
    spec:
      containers:
      - name: githubactionspoc
        image: docker.io/shazindia86/githubactionsdemo:latest
        ports:
        - name:  http
          containerPort: 8080
          protocol: TCP