apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: githubactions-harness-hpa-poc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: githubactionspoc
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 20
