apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: githubactionspoc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: githubactions-harness-poc
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
