name: Deploy to AKS Cluster
#on: [push]
on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: Azure/docker-login@v1
      with:
        login-server: githubactionsharness.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - run: |
        docker build . -t githubactionsharness.azurecr.io/k8sflask:${{ github.sha }}
        docker push githubactionsharness.azurecr.io/k8sflask:${{ github.sha }}
      
    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: Github-Harness-PoC
        resource-group: Aks-Harness
        
    - uses: Azure/k8s-create-secret@v1
      with:
        container-registry-url: githubactionsharness.azurecr.io
        container-registry-username: ${{ secrets.ACR_USERNAME }}
        container-registry-password: ${{ secrets.ACR_PASSWORD }}
        secret-name: k8s-secret

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          manifest/kubernetes-manifest.yaml
        images: |
          githubactionsharness.azurecr.io/k8sflask:${{ github.sha }}
        imagepullsecrets: |
          k8s-secret