name: Deploy to AKS Cluster
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dummy Step
      run: echo "This is a dummy job for CD workflow."

      needs: ci
      if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'

    - name: Checkout code
      uses: actions/checkout@v2

    - uses: Azure/docker-login@v1
      with:
        login-server: githubactionsharness.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: Github-Harness-PoC
        resource-group: Aks-Harness
        
    - uses: Azure/k8s-create-secret@v1
      with:
        container-registry-url: githubactionsharness.azurecr.io
        container-registry-username: ${{ secrets.ACR_USERNAME }}
        container-registry-password: ${{ secrets.ACR_PASSWORD }}
        secret-name: k8s-secret

    - uses: Azure/k8s-deploy@v3
      with:
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: githubactionsharness.azurecr.io/githubactionsharness:latest
        imagepullsecrets: k8s-secret
