name: CI 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'
        cache-dependency-path: | # optional
            sub-project/*.gradle*
            sub-project/**/gradle-wrapper.properties
     
    - run: ./gradlew build --no-daemon

    #- name: Grant execute permission for gradlew
    #  run: chmod +x gradlew

    #- name: Build with Gradle
    #  run: ./gradlew build

    - name: Login to Azure Container  Registery
      uses: docker/login-action@v3
      with:
        registry: githubactionsharness.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
            docker build -t githubactionsharness.azurecr.io/githubactionsharness:latest .
            docker push githubactionsharness.azurecr.io/githubactionsharness:latest
    
    #- name: ACR Scanning
     # uses: azure/container-scan@v0
     # with:
      #  image-name: githubactionsharness.azurecr.io/githubactionsharness:${{ github.sha }} # loginServerlUrl/ would be empty if it's hosted on dockerhub; ${{ github.sha }} could also be replaced with any desired image tag
       # username: ${{ secrets.ACR_USERNAME }}
       # password: ${{ secrets.ACR_PASSWORD }}
